export { analyzeMarkdown, type AnalysisReport, type DocumentType } from "./core/analyze.js";
export { normalizeMarkdown, lintMarkdown, boldTableHeaders, type NormalizationReport } from "./core/normalize.js";
export { normalizeHeadingNumbers } from "./core/headings.js";
export { preprocessMarkdown, transformHeading, type PreprocessOptions, type RainbowConfig } from "./core/preprocess.js";
export { convertToLarkTables } from "./core/lark-table.js";
export { splitMarkdown, type Chunk, type ChunkConfig } from "./core/chunked.js";
export { computePatches, executePatches } from "./patch/patch.js";
export { highlightExtract, highlightApply, saveBatches, type TitleEntry, type KeywordEntry } from "./core/highlight.js";
export { processImages, extractImageRefs } from "./image/images.js";
export { verifyDoc, formatReport } from "./verify/verify.js";
export { LarkCli, type AuthStatus, type ApiResult, type CliOptions } from "./cli.js";
export { WikiClient } from "./wiki/wiki-client.js";
export { parseWikiUrl, type ParsedWikiUrl } from "./wiki/wiki-url.js";
export type { WikiNode, SyncNodeResult, SyncOptions } from "./wiki/wiki-types.js";
